# Transforming Code into Idiomatic Python
- Replace traditional index manipulation with Python core looping idiomatic

In [1]:
# Looping over a range of numbers - Traditional Approch


for i in [0,1,2,3,4,5]:
    print(i**2,end="  ")

0  1  4  9  16  25  

In [2]:
# Idiomatic programming new approch


for i in range(6):
    print(i**2,end="  ")

0  1  4  9  16  25  

## Loop Over A Collection 

In [3]:
# printing loop over a collection - Traditional Approch

colors = ['red','green','yellow','purple','blue']
for i in range(len(colors)):
    print(colors[i],end="  ")

red  green  yellow  purple  blue  

In [5]:
# printing loop over a collection new approch

for color in colors:
    print(color,end="  ")

red  green  yellow  purple  blue  

## Looping Backwards

In [8]:
# printing loop backwards - Traditional Approch

colors = ['red','green','yellow','purple','blue']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end="  ")

IndexError: string index out of range

In [7]:
# printing loop over a collection new approch

for color in reversed(colors):
    print(color,end="  ")

blue  purple  yellow  green  red  

## Looping in Sorted list

In [9]:
# printing sorted loop  - Traditional Approch

colors = ['red','green','yellow','purple','blue']
for color in sorted(colors):
    print(color,end="  ")

blue  green  purple  red  yellow  

In [10]:
# printing sorted loop  - new Approch

colors = ['red','green','yellow','purple','blue']
for color in sorted(colors,reverse=True):
    print(color,end="  ")

yellow  red  purple  green  blue  

# Pandas

In [11]:
import pandas as pd

In [12]:
dt = {'id':[11,12,13,14,15],
      'name':['A','B','C','D','E'],
      'company':['aa','bb','cc','dd','ee'],
      'address':['hyd','hyd','hyd','hyd','hyd']}
mydt = pd.DataFrame(dt)

In [14]:
print(mydt)

   id name company address
0  11    A      aa     hyd
1  12    B      bb     hyd
2  13    C      cc     hyd
3  14    D      dd     hyd
4  15    E      ee     hyd


In [15]:
import os

In [16]:
os.chdir("D:\\MyData\\") # saves to creation location

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\MyData\\'

In [17]:
mydt.to_csv('WorkingFile.csv',index = False)

## Reading the Data from CSV file

In [22]:
mydata1 = pd.read_csv('WorkingFile.csv',skiprows=1,names = ["custid","name","company","address"])

In [23]:
print(mydata1)

   custid name company address
0      11    A      aa     hyd
1      12    B      bb     hyd
2      13    C      cc     hyd
3      14    D      dd     hyd
4      15    E      ee     hyd


In [24]:
# skipping the rows

mydata1 = pd.read_csv('WorkingFile.csv',skiprows=[1,2],names = ["custid","name","company","address"])

In [25]:
print(mydata1)

  custid  name  company  address
0     id  name  company  address
1     13     C       cc      hyd
2     14     D       dd      hyd
3     15     E       ee      hyd


In [26]:
pwd

'C:\\Users\\239'

## print only two coloumns
## print the large value from custid coloumn -- max
## print the least value from custid coloumn -- min
## Average os custid coloumn 

### Numpy- Working with Multi-Dimensional arrays
- Numpy arrays is a bit like Python list
- Numpy array is a data structure of Numpy Lib
- It's a short name for "Numeric Python" or "Numerical Python"


In [27]:
import numpy as np

In [28]:
    li = [1,2,3,4,5]
    print(li,end=" ")

[1, 2, 3, 4, 5] 

In [29]:
array = np.array(li)
print(array)

[1 2 3 4 5]


In [30]:
# arrays

a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [31]:
# arrays

a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
a1 = np.array([(1,2,3)])
a2 = np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
